Deploy: deploy_preproduction accepts tags

diff --git a/.bin/deploy_preproduction b/.bin/deploy_preproduction
--- a/.bin/deploy_preproduction
+++ b/.bin/deploy_preproduction
@@ -17,6 +17,8 @@ app_name='chefcito'
 app_repository='origin'
 app_release="$1"
 app_branch="release/$1"
+app_tag="version/$1"
+app_checkout="release/$1"
 
 app_gluerokku_name='chefcito-pre'
 app_gluerokku_env='preproduction'
@@ -30,11 +32,32 @@ check_dir() {
 	fi
 }
 
+set_checkout() {
+	branch=$(git branch --list "$app_branch")
+	if [[ -z "$branch" ]]; then
+		tag=$(git tag --list "$app_tag")
+		if [[ -z "$tag" ]]; then
+			echo "Invalid release version: $app_release"
+			return 1
+		else
+			app_checkout="$app_tag"
+		fi
+	fi
+}
+
 check_branch() {
 	branch=$(git branch --list "$app_branch")
 	if [[ -z "$branch" ]]; then
 		echo "Invalid release version: $app_release"
-		exit 1
+		return 1
+	fi
+}
+
+check_tag() {
+	tag=$(git tag --list "$app_tag")
+	if [[ -z "$tag" ]]; then
+		echo "Invalid tag version: $app_release"
+		return 1
 	fi
 }
 
@@ -44,11 +67,13 @@ color_no='\033[0m'
 color_icon=$'\360\237\215\211'
 
 check_dir
-check_branch
+set_checkout
 echo "${color_icon}  ${color_1}===> ${color_2}Update${color_no}"
+git checkout $app_checkout || exit 1
 git pull "$app_repository" || exit 1
 echo "${color_icon}  ${color_1}===> ${color_2}Build${color_no}"
 grunt "$app_gluerokku_env" || exit 1
 echo "${color_icon}  ${color_1}===> ${color_2}Deploy${color_no}"
-git push -v "$app_gluerokku_repository" "$app_branch:master" || exit 1
+git push -v "$app_gluerokku_repository" "$app_checkout:master" || exit 1
 echo "${color_icon}  ${color_1}===> ${color_2}Done!${color_no}"
+
